[tool.poetry]
name = "devmentor-be103-python"
version = "0.1.0"
description = ""
authors = ["Jonny <ji394su311203106@gmail.com>"]
readme = "README.md"
packages = [{include = "devmentor-BE103-python"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
sqlalchemy = "^2.0.25"
pymysql = "^1.1.0"
cryptography = "^42.0.1"
alembic = "^1.13.1"
python-multipart = "^0.0.9"
pyjwt = "^2.9.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
requests = "^2.32.3"
email-validator = "^2.2.0"
pandas = "^2.2.3"
matplotlib = "^3.9.2"
apscheduler = "^3.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
